/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/login/AuthForm.vue')['default']
    GameHeader: typeof import('./src/components/GameHeader.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Logo: typeof import('./src/components/icons/Logo.vue')['default']
    Map: typeof import('./src/components/game/map/Map.vue')['default']
    MapLine: typeof import('./src/components/game/map/MapLine.vue')['default']
    MenuHeader: typeof import('./src/components/MenuHeader.vue')['default']
    ModalBase: typeof import('./src/components/ModalBase.vue')['default']
    MPokemon: typeof import('./src/components/modals/MPokemon.vue')['default']
    MPoket: typeof import('./src/components/modals/MPoket.vue')['default']
    MProfile: typeof import('./src/components/modals/MProfile.vue')['default']
    Pokemon: typeof import('./src/components/Pokemon.vue')['default']
    PokemonPreviewBox: typeof import('./src/components/PokemonPreviewBox.vue')['default']
    RegisterForm: typeof import('./src/components/login/RegisterForm.vue')['default']
    Room: typeof import('./src/components/game/map/Room.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectStartPokemon: typeof import('./src/components/login/SelectStartPokemon.vue')['default']
  }
}
